defmodule Mix.Tasks.SwarmCode.Settings do
  use Mix.Task
  @shortdoc "Prints or checks docs/settings.md, generated from the settings registry"
  @requirements ["compile"]

  @moduledoc """
  The settings reference (pass 74, spec §3.10.4) is generated from the
  registry, never hand-written: one table per section (key, label, scope,
  type, default, when it applies, the environment or flag that overrides it).

      mix swarm_code.settings            # print the Markdown
      mix swarm_code.settings --write    # write docs/settings.md
      mix swarm_code.settings --check    # exit 1 if the file and the registry disagree

  Run from `apps/swarm_code_cli`; the docs directory is the umbrella's.
  """

  alias SwarmCode.Settings.{Entry, Registry, Sections, TextValue}

  @impl Mix.Task
  def run(args) do
    unless Mix.Project.config()[:app] == :swarm_code_cli and not Mix.Project.umbrella?(),
      do: Mix.raise("Run this task from apps/swarm_code_cli")

    rendered = render()

    case args do
      [] ->
        IO.write(rendered)

      ["--write"] ->
        File.write!(path(), rendered)
        Mix.shell().info("wrote #{path()}")

      ["--check"] ->
        if File.exists?(path()) and File.read!(path()) == rendered do
          Mix.shell().info("#{path()} matches the settings registry")
        else
          Mix.raise("#{path()} is stale; run `mix swarm_code.settings --write`")
        end

      _ ->
        Mix.raise("Expected no arguments, --write or --check")
    end
  end

  @doc false
  def path, do: Path.expand("../../docs/settings.md", File.cwd!())

  @doc "The Markdown reference."
  @spec render() :: String.t()
  def render do
    sections =
      for section <- Sections.all(),
          entries = entries(section.id),
          entries != [],
          do: section_table(section, entries)

    IO.iodata_to_binary([
      "# Settings\n\n",
      "Generated by `mix swarm_code.settings --write` from the settings registry; do not edit.\n",
      "Open them with `swarmcode settings [QUERY]` or `/settings` in a session, or change them\n",
      "from scripts with `swarmcode config set KEY VALUE` (`swarmcode config help`).\n\n",
      "Scopes: `global` (the database, shared with the desktop app), `project` (the project row),\n",
      "`session` (this conversation), `cli` (`cli.json`, this terminal only), `project_file`\n",
      "(`.swarm_code/config.json`, read-only here).\n",
      Enum.map(sections, &["\n", &1])
    ])
  end

  defp entries(section) do
    section
    |> Registry.for_section()
    |> Enum.filter(&Entry.scalar?/1)
  end

  defp section_table(section, entries) do
    [
      "## ",
      section.title,
      "\n\n",
      "| Key | Label | Scope | Type | Default | Applies | Override |\n",
      "|---|---|---|---|---|---|---|\n",
      Enum.map(entries, &row/1)
    ]
  end

  defp row(entry) do
    cells = [
      "`" <> entry.key <> "`",
      entry.label,
      Atom.to_string(entry.scope),
      Atom.to_string(entry.type),
      default(entry),
      applies(entry.applies),
      override(entry)
    ]

    ["| ", Enum.map_join(cells, " | ", &escape/1), " |\n"]
  end

  defp default(%Entry{default: nil} = entry), do: entry.null_label || "—"

  defp default(entry) do
    TextValue.format(entry, entry.default)
  rescue
    _ -> inspect(entry.default)
  end

  defp applies(value) when is_atom(value),
    do: value |> Atom.to_string() |> String.replace("_", " ")

  defp applies(value), do: to_string(value)

  defp override(entry) do
    env = for name <- List.wrap(entry.env), is_binary(name), do: "`#{name}`"
    flag = if is_binary(entry.flag), do: ["`#{entry.flag}`"], else: []

    case env ++ flag do
      [] -> "—"
      names -> Enum.join(names, ", ")
    end
  end

  defp escape(text) do
    text
    |> to_string()
    |> String.replace("|", "\\|")
    |> String.replace("\n", " ")
  end
end
