defmodule SwarmCode.Settings.Registry.Limits do
  @moduledoc false
  # §2.9 Agents & limits: limits, isolation and the model's shell.
  import SwarmCode.Settings.Registry.Build

  @entries [
    global("limits.max_concurrent_agents", :agents_limits, "Max concurrent agents",
      group: "limits",
      description:
        "Per run: sub-agents of one swarm or one chat turn working at once; research has its own cap.",
      storage: {:setting, :max_concurrent_agents},
      type: :integer,
      min: 1,
      max: 16,
      default: 4,
      applies: :next_spawn,
      shared: true,
      synonyms: ["concurrency", "parallel agents"],
      parity: "D§12"
    ),
    global("limits.max_agent_depth", :agents_limits, "Max agent depth",
      group: "limits",
      description: "Nesting of spawn_agent.",
      storage: {:setting, :max_agent_depth},
      type: :enum,
      choices: choices([{1, "1"}, {2, "2"}, {3, "3"}]),
      default: 2,
      messages: %{inclusion: "must be between 1 and 3"},
      applies: :next_spawn,
      shared: true,
      parity: "D§12"
    ),
    global("limits.max_agent_turns", :agents_limits, "Max agent turns",
      group: "limits",
      description: "Think/act loops per agent.",
      storage: {:setting, :max_agent_turns},
      type: :integer,
      min: 1,
      max: 200,
      default: 60,
      applies: :next_spawn,
      shared: true,
      parity: "D§12"
    ),
    global("limits.sub_agent_timeout", :agents_limits, "Sub-agent time limit",
      group: "limits",
      description: "A worker that runs longer is stopped and its partial work reported.",
      storage: {:setting, :sub_agent_timeout_s},
      type: :duration,
      unit: :s,
      min: 60,
      max: 86_400,
      step: 60,
      big_step: 1_800,
      special: %{0 => "no limit"},
      default: 1_800,
      messages: %{range: "must be 0 (no limit) or between 60 and 86400"},
      applies: :next_spawn,
      shared: true,
      parity: "D§12"
    ),
    global("limits.workflow_budget", :agents_limits, "Workflow agent budget",
      group: "limits",
      description: "The most agents one workflow run may spend; a project file cannot set it.",
      storage: {:setting, :workflow_budget},
      type: :integer,
      min: 1,
      max: 1024,
      big_step: 32,
      default: 128,
      applies: :next_turn,
      shared: true,
      parity: "D§12"
    ),
    global("limits.workflow_max_live", :agents_limits, "Max live workflow agents",
      group: "limits",
      description: "At the same time (RAM).",
      storage: {:setting, :workflow_max_live},
      type: :integer,
      min: 1,
      max: 64,
      big_step: 8,
      default: 16,
      applies: :next_turn,
      shared: true,
      parity: "D§12"
    ),
    global("limits.command_timeout", :agents_limits, "Command timeout",
      group: "limits",
      description: "The least every shell command gets; a call may ask for more.",
      storage: {:setting, :command_timeout_ms},
      type: :duration,
      unit: :ms,
      min: 1_000,
      max: 600_000,
      step: 1_000,
      big_step: 60_000,
      default: 120_000,
      applies: :next_turn,
      shared: true,
      parity: "D§12"
    ),
    global("limits.tool_timeout", :agents_limits, "Tool timeout",
      group: "limits",
      description: "Web fetch, web search, MCP and language-server calls.",
      storage: {:setting, :tool_timeout_ms},
      type: :duration,
      unit: :ms,
      min: 1_000,
      max: 600_000,
      step: 1_000,
      big_step: 60_000,
      default: 120_000,
      applies: :next_request,
      shared: true,
      parity: "D§12"
    ),
    global("isolation.worktrees", :agents_limits, "Isolate sub-agents",
      group: "isolation",
      description:
        "Each sub-agent works in its own copy; the lead merges with integrate_agent. Git projects only.",
      storage: {:setting, :worktrees_enabled},
      type: :toggle,
      default: true,
      applies: :next_spawn,
      shared: true,
      synonyms: ["worktrees"],
      parity: "D§12"
    ),
    global("isolation.backend", :agents_limits, "How to isolate",
      group: "isolation",
      storage: {:setting, :isolation_backend},
      type: :enum,
      choices:
        choices([
          {"auto", "Auto (APFS clone when available, else git worktree)"},
          {"clone", "APFS clone"},
          {"worktree", "Git worktree"}
        ]),
      default: "auto",
      applies: :next_spawn,
      shared: true,
      parity: "D§12"
    ),
    global("shell.env_scrub", :agents_limits, "Hide secrets from commands",
      group: "shell",
      description:
        "Drops variables named like API_KEY, *_KEY, SECRET, TOKEN, PASSWORD, PASSWD, CREDENTIAL, *_PAT from run_command; MCP servers and hooks always use the default scrub.",
      storage: {:setting, :shell_env_scrub},
      type: :toggle,
      default: true,
      applies: :next_turn,
      shared: true,
      synonyms: ["scrub", "env scrub"],
      parity: "D§12"
    ),
    global("shell.env_keep", :agents_limits, "Keep these variables",
      group: "shell",
      description: "Names kept despite the scrub.",
      storage: {:setting, :shell_env_keep},
      type: :list,
      item: :env_name,
      default: ["GITHUB_TOKEN", "GH_TOKEN"],
      validate: [{:list_max, 64}, :unique_items, {:item, :env_name}],
      applies: :next_turn,
      shared: true,
      parity: "D§12"
    ),
    global("shell.path", :agents_limits, "Shell",
      group: "shell",
      description: "Blank detects $SHELL. SWARM_CODE_SHELL wins while it is set.",
      storage: {:setting, :shell_path},
      type: :path,
      nullable: true,
      null_label: "detect ($SHELL)",
      layers: [:env, :global, :default],
      env: ["SWARM_CODE_SHELL"],
      validate: [{:svc, :executable_path}],
      messages: %{
        executable_path: "is not an executable file",
        not_a_file: "is not a file on this machine"
      },
      example: "/bin/sh",
      applies: :next_turn,
      shared: true,
      parity: "D§12"
    ),
    global("shell.login", :agents_limits, "Login shell",
      group: "shell",
      description: "-lc, so .zprofile/.profile PATH additions (mise, asdf, nvm, brew) apply.",
      storage: {:setting, :shell_login},
      type: :toggle,
      default: true,
      applies: :next_turn,
      shared: true,
      parity: "D§12"
    )
  ]

  def entries, do: @entries
end
