defmodule SwarmCode.Settings.Registry.Models do
  @moduledoc false
  # §2.2 Models & effort: the global model pairs and default efforts.
  import SwarmCode.Settings.Registry.Build

  @model_checks [{:svc, :provider_exists}]
  @effort_checks [{:format, "^[a-z0-9][a-z0-9_-]{0,23}$"}]

  @entries [
    global("models.chat", :models_effort, "Chat model",
      group: "new conversations",
      description: "The model a new conversation's chat turns use.",
      storage: {:setting_pair, :default_chat_provider_id, :default_chat_model},
      type: :model,
      nullable: true,
      null_label: "the first provider with a key",
      validate: @model_checks,
      messages: %{provider_exists: "that provider no longer exists"},
      applies: :new_conversations,
      shared: true,
      synonyms: ["model", "chat model", "default model"],
      parity: "D§1a"
    ),
    global("models.sub_agent", :models_effort, "Sub-agent model",
      group: "new conversations",
      description: "The model of spawned workers and /swarm runs; the judge falls back to it.",
      storage: {:setting_pair, :default_swarm_provider_id, :default_swarm_model},
      type: :model,
      nullable: true,
      null_label: "the first provider with a key",
      validate: @model_checks,
      messages: %{provider_exists: "that provider no longer exists"},
      applies: :next_spawn,
      shared: true,
      synonyms: ["swarm model", "worker model"],
      parity: "D§1a"
    ),
    global("models.scheduled", :models_effort, "Scheduled task model",
      group: "new conversations",
      description:
        "The model of scheduled tasks without their own model. Schedules run only while the desktop app runs.",
      storage: {:setting_pair, :default_scheduled_provider_id, :default_scheduled_model},
      type: :model,
      nullable: true,
      null_label: "the chat model",
      validate: @model_checks,
      messages: %{provider_exists: "that provider no longer exists"},
      applies: :desktop,
      scheduler_only: true,
      shared: true,
      parity: "D§1a, I§13"
    ),
    global("models.workflow", :models_effort, "Workflow model",
      group: "new conversations",
      description: "The model of workflow runs without their own model.",
      storage: {:setting_pair, :default_workflow_provider_id, :default_workflow_model},
      type: :model,
      nullable: true,
      null_label: "the chat model",
      validate: @model_checks,
      messages: %{provider_exists: "that provider no longer exists"},
      applies: :next_turn,
      shared: true,
      parity: "D§1a"
    ),
    global("models.implementer", :models_effort, "Implementer model (consensus)",
      group: "new conversations",
      description: "Who implements a judged plan in consensus mode.",
      storage: {:setting_pair, :default_implementer_provider_id, :default_implementer_model},
      type: :model,
      nullable: true,
      null_label: "the planner implements",
      validate: @model_checks,
      messages: %{provider_exists: "that provider no longer exists"},
      applies: :next_turn,
      shared: true,
      parity: "D§1a"
    ),
    action(
      "models.fetch_all",
      :models_effort,
      "Fetch every provider's models",
      "provider.fetch_all",
      group: "new conversations",
      description: "Lists every provider's models and shows what changed; apply per provider.",
      parity: "D§1c"
    ),
    global("efforts.default", :models_effort, "Default effort",
      group: "default efforts",
      description: "Reasoning effort of chat turns in conversations without their own effort.",
      storage: {:setting, :default_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :chat_default},
      default: "medium",
      layers: [:global, :project_file, :default],
      ignored_layers: [{:project_file, "effort"}],
      validate: @effort_checks,
      applies: :next_turn,
      shared: true,
      synonyms: ["effort", "reasoning effort"],
      parity: "D§1b"
    ),
    global("efforts.sub_agent", :models_effort, "Sub-agent effort",
      group: "default efforts",
      description: "Reasoning effort of spawned workers.",
      storage: {:setting, :default_swarm_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :swarm_default},
      default: "medium",
      layers: [:global, :project_file, :default],
      ignored_layers: [{:project_file, "swarm_effort"}],
      validate: @effort_checks,
      applies: :next_spawn,
      shared: true,
      synonyms: ["swarm effort"],
      parity: "D§1b"
    ),
    global("efforts.scheduled", :models_effort, "Scheduled effort",
      group: "default efforts",
      description:
        "Reasoning effort of scheduled tasks. Schedules run only while the desktop app runs.",
      storage: {:setting, :default_scheduled_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :scheduled_default},
      nullable: true,
      null_label: "same as the default effort",
      validate: @effort_checks,
      applies: :desktop,
      scheduler_only: true,
      shared: true,
      parity: "D§1b"
    ),
    global("efforts.workflow", :models_effort, "Workflow effort",
      group: "default efforts",
      description: "Reasoning effort of workflow runs.",
      storage: {:setting, :default_workflow_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :workflow_default},
      nullable: true,
      null_label: "same as the default effort",
      validate: @effort_checks,
      applies: :next_turn,
      shared: true,
      parity: "D§1b"
    ),
    global("efforts.implementer", :models_effort, "Implementer effort",
      group: "default efforts",
      description: "Reasoning effort of a consensus implementation.",
      storage: {:setting, :default_implementer_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :implementer_default},
      nullable: true,
      null_label: "medium (not set)",
      validate: @effort_checks,
      applies: :next_turn,
      shared: true,
      parity: "D§1b"
    )
  ]

  def entries, do: @entries
end
