defmodule SwarmCode.Settings.Registry.Research do
  @moduledoc false
  # §2.6 Deep research.
  import SwarmCode.Settings.Registry.Build

  @effort [{:format, "^[a-z0-9][a-z0-9_-]{0,23}$"}]
  @model_msg %{provider_exists: "that provider no longer exists"}
  @domains [{:list_max, 64}, :unique_items, {:item, :domain}]

  @entries [
    global("research.level", :deep_research, "Default level",
      storage: {:setting, :research_level},
      type: :enum,
      choices:
        choices([
          {"low", "Fastest", "1 round · 4 agents"},
          {"medium", "Medium", "2 rounds · 3 agents each"},
          {"high", "High", "3 rounds · 4 agents each"},
          {"ultra", "Ultra", "4 rounds · 10 agents each"}
        ]),
      default: "medium",
      applies: :next_research,
      shared: true,
      synonyms: ["research level", "depth"],
      parity: "D§2c"
    ),
    global("research.max_live", :deep_research, "Agents in flight at once",
      description: "Research's own cap on agents working at the same time.",
      storage: {:setting, :research_max_live},
      type: :integer,
      min: 1,
      max: 32,
      default: 10,
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.max_sources", :deep_research, "Pages each agent must read",
      storage: {:setting, :research_max_sources},
      type: :integer,
      min: 1,
      max: 20,
      default: 5,
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.recency_days", :deep_research, "Only sources newer than",
      description: "Research searches only.",
      storage: {:setting, :research_recency_days},
      type: :integer,
      unit: :days,
      min: 1,
      max: 3650,
      big_step: 30,
      nullable: true,
      null_label: "any age",
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.agent_timeout", :deep_research, "Seconds an agent may take",
      description: "The reporter gets twice this.",
      storage: {:setting, :research_agent_timeout_s},
      type: :duration,
      unit: :s,
      min: 60,
      max: 3600,
      step: 30,
      big_step: 300,
      default: 600,
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.max_retries", :deep_research, "Retries after a timeout",
      storage: {:setting, :research_max_retries},
      type: :integer,
      min: 0,
      max: 3,
      default: 1,
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.retry_timeouts", :deep_research, "Retry timed-out agents",
      description: "Off: the partial note is what the round gets.",
      storage: {:setting, :research_retry_timeouts},
      type: :toggle,
      default: true,
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.headlines", :deep_research, "A headline per round",
      description: "One small call per round at the lead tier.",
      storage: {:setting, :research_headlines},
      type: :toggle,
      default: true,
      applies: :next_research,
      shared: true,
      parity: "D§2d"
    ),
    global("research.auto_design", :deep_research, "Designed HTML report",
      storage: {:setting, :research_auto_design},
      type: :enum,
      choices:
        choices([
          {"deep", "After every deep research"},
          {"all", "After every research, Fastest too"},
          {"never", "Only when I ask"}
        ]),
      default: "deep",
      applies: :next_research,
      shared: true,
      parity: "D§2e"
    ),
    global("research.include_domains", :deep_research, "Only these domains",
      description: "Research searches only.",
      storage: {:setting, :research_include_domains},
      type: :list,
      item: :domain,
      default: [],
      validate: @domains,
      applies: :next_research,
      shared: true,
      parity: "D§2f"
    ),
    global("research.exclude_domains", :deep_research, "Never these domains",
      storage: {:setting, :research_exclude_domains},
      type: :list,
      item: :domain,
      default: [],
      validate: @domains,
      applies: :next_research,
      shared: true,
      parity: "D§2f"
    ),
    global("research.lead_model", :deep_research, "Lead model",
      group: "models",
      description: "Plans each round and writes the headline.",
      storage: {:setting_pair, :research_lead_provider_id, :research_lead_model},
      type: :model,
      nullable: true,
      null_label: "the sub-agent model",
      validate: [{:svc, :provider_exists}],
      messages: @model_msg,
      applies: :next_research,
      shared: true,
      parity: "D§2g"
    ),
    global("research.lead_effort", :deep_research, "Lead effort",
      group: "models",
      storage: {:setting, :research_lead_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :research_lead},
      nullable: true,
      null_label: "default",
      validate: @effort,
      applies: :next_research,
      shared: true,
      parity: "D§2g"
    ),
    global("research.worker_model", :deep_research, "Worker model",
      group: "models",
      description: "Searches and reads; an ultra research runs forty.",
      storage: {:setting_pair, :research_worker_provider_id, :research_worker_model},
      type: :model,
      nullable: true,
      null_label: "the sub-agent model",
      validate: [{:svc, :provider_exists}],
      messages: @model_msg,
      applies: :next_research,
      shared: true,
      parity: "D§2g"
    ),
    global("research.worker_effort", :deep_research, "Worker effort",
      group: "models",
      storage: {:setting, :research_worker_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :research_worker},
      nullable: true,
      null_label: "default",
      validate: @effort,
      applies: :next_research,
      shared: true,
      parity: "D§2g"
    ),
    global("research.reporter_model", :deep_research, "Reporter model",
      group: "models",
      description: "Writes result.md and report.html.",
      storage: {:setting_pair, :research_reporter_provider_id, :research_reporter_model},
      type: :model,
      nullable: true,
      null_label: "the sub-agent model",
      validate: [{:svc, :provider_exists}],
      messages: @model_msg,
      applies: :next_research,
      shared: true,
      parity: "D§2g"
    ),
    global("research.reporter_effort", :deep_research, "Reporter effort",
      group: "models",
      storage: {:setting, :research_reporter_effort},
      type: :effort,
      dynamic_choices: {:effort_of, :research_reporter},
      nullable: true,
      null_label: "default",
      validate: @effort,
      applies: :next_research,
      shared: true,
      parity: "D§2g"
    ),
    fact("research.root", :deep_research, "Research folder", :research_root,
      description: "o opens it, y copies the path.",
      parity: "D§2h"
    )
  ]

  def entries, do: @entries
end
