defmodule SwarmCodeCLI.UI.Keymap.Docs do
  @moduledoc """
  `docs/keybindings.md`, rendered from the binding table.

  The file is generated by `mix swarm_code.keymap` and checked by a test, so
  the reference can never describe a key the shell does not have.
  """

  alias SwarmCodeCLI.UI.Keymap.Bindings
  alias SwarmCodeCLI.UI.Projector.KeyLabel

  @titles [
    main: "Transcript (main)",
    inspector: "Inspector",
    composer: "Composer",
    composer_normal: "Composer, vim NORMAL",
    composer_visual: "Composer, vim VISUAL",
    picker: "Pickers: command palette, run palette, runs dashboard, go-to",
    dialog: "Dialogs",
    field: "Text fields inside dialogs",
    overlay: "Agent overlay",
    hint: "Hint mode (Ctrl-F)",
    settings: "Settings: browsing the rail and the pages",
    settings_search: "Settings: the search row and the `:` command line",
    settings_edit: "Settings: a value being edited",
    settings_paste: "Settings: pasting a key",
    settings_capture: "Settings: capturing a key (Key bindings)",
    settings_picker: "Settings: a picker",
    settings_popover: "Settings: a confirmation, the key help or the leave question"
  ]

  @groups [
    navigate: "Navigate",
    focus: "Focus",
    runs: "Runs",
    act: "Act",
    layers: "Layers",
    edit: "Edit",
    vim: "Vim",
    session: "Session",
    settings: "Settings"
  ]

  @mouse_note "Mouse: the wheel scrolls the pane under the pointer (the transcript, the side " <>
                "panel, the agent overlay, the pager), three lines a notch. While wheel reports " <>
                "are on, Shift-drag (Option-drag in Terminal.app and iTerm2) selects text; " <>
                "`/mouse off` gives the terminal its own selection back."

  # cli74 U1-2: the settings layer's chapter (spec §3.9, §4.3).
  @settings_intro """

  # Settings

  `F2` or `/settings` (also `/config`, `/prefs`) opens Settings over the
  shell; `/settings <words>` opens it at the matching section or setting.
  Esc goes back one level and closes Settings at a section page; `q` closes
  it from anywhere. The letters below act on the focused row, and the footer
  lists only the letters that row answers to, in its own words (`t test the
  connection`, `R restart now`). With the vim keymap `j`, `k`, `g g` and `G`
  also move. Ctrl-C clears a text, then cancels; on a page it closes
  Settings, and a second Ctrl-C quits as in the shell.

  Every key except Esc, Enter, the arrows, Ctrl-C, `?`/`F1` and Ctrl-S can be
  changed on Settings › Keys & input (stored in cli.json's `keys`). If a
  change leaves you without a way back, run `swarmcode config reset
  terminal.keys` in a shell.
  """

  @doc """
  pass73 T9: the sentence about the mouse, for this reference and the help
  sheet (`?`) while wheel reports are on.
  """
  @spec mouse_note() :: binary()
  def mouse_note, do: @mouse_note

  @doc "The reference as Markdown, ending in a newline."
  @spec render() :: binary()
  def render do
    header = """
    # Keyboard reference

    Generated by `mix swarm_code.keymap` from `SwarmCodeCLI.UI.Keymap.Bindings`.
    Do not edit by hand: `mix swarm_code.keymap --check` fails when this file
    and the table disagree.

    Keys are read against one *context* at a time, chosen from where the focus
    is and which layer is on top. `?` (or `F1` inside a text field) shows the
    same list for the current context on screen. Vim's NORMAL and VISUAL modes
    exist only with the vim keymap on (`SWARM_KEYMAP=vim`, or "Vim mode" in
    the command palette).

    #{@mouse_note}
    """

    shell = Bindings.contexts() -- Bindings.settings_contexts()

    header <>
      Enum.map_join(shell, "", &context/1) <>
      @settings_intro <> Enum.map_join(Bindings.settings_contexts(), "", &context/1)
  end

  @doc "The human title of `context`."
  @spec title(atom()) :: binary()
  def title(context), do: Keyword.fetch!(@titles, context)

  @doc "The human title of `group`."
  @spec group_title(atom()) :: binary()
  def group_title(group), do: Keyword.fetch!(@groups, group)

  defp context(context) do
    bindings = Bindings.for_context(context)

    sections =
      Bindings.groups()
      |> Enum.map(fn group -> {group, Enum.filter(bindings, &(&1.group == group))} end)
      |> Enum.reject(fn {_group, rows} -> rows == [] end)
      |> Enum.map_join("", fn {group, rows} -> section(group, rows, context) end)

    "\n## " <> title(context) <> "\n" <> sections
  end

  defp section(group, rows, context) do
    table =
      Enum.map_join(rows, "\n", fn binding ->
        "| " <> keys(binding, context) <> " | " <> binding.help <> " |"
      end)

    "\n### " <> group_title(group) <> "\n\n| Keys | Does |\n|---|---|\n" <> table <> "\n"
  end

  # Only the spellings that reach the binding in this context: `?` opens help
  # in main, but in the composer it types, and only `F1` is listed there.
  defp keys(binding, context) do
    binding
    |> Bindings.keys_in_context(context)
    |> KeyLabel.labels(false)
    |> Enum.map_join(" / ", &("`" <> &1 <> "`"))
  end
end
