defmodule SwarmCodeCLI.UI.Keymap.Docs do
  @moduledoc """
  `docs/keybindings.md`, rendered from the binding table.

  The file is generated by `mix swarm_code.keymap` and checked by a test, so
  the reference can never describe a key the shell does not have.
  """

  alias SwarmCodeCLI.UI.Keymap.Bindings
  alias SwarmCodeCLI.UI.Projector.KeyLabel

  @titles [
    main: "Transcript (main)",
    inspector: "Inspector",
    composer: "Composer",
    composer_normal: "Composer, vim NORMAL",
    composer_visual: "Composer, vim VISUAL",
    picker: "Pickers: command palette, run palette, runs dashboard, go-to",
    dialog: "Dialogs",
    field: "Text fields inside dialogs",
    overlay: "Agent overlay",
    hint: "Hint mode (Ctrl-F)"
  ]

  @groups [
    navigate: "Navigate",
    focus: "Focus",
    runs: "Runs",
    act: "Act",
    layers: "Layers",
    edit: "Edit",
    vim: "Vim",
    session: "Session"
  ]

  @mouse_note "Mouse: the wheel scrolls the pane under the pointer (the transcript, the side " <>
                "panel, the agent overlay, the pager), three lines a notch. While wheel reports " <>
                "are on, Shift-drag (Option-drag in Terminal.app and iTerm2) selects text; " <>
                "`/mouse off` gives the terminal its own selection back."

  @doc """
  pass73 T9: the sentence about the mouse, for this reference and the help
  sheet (`?`) while wheel reports are on.
  """
  @spec mouse_note() :: binary()
  def mouse_note, do: @mouse_note

  @doc "The reference as Markdown, ending in a newline."
  @spec render() :: binary()
  def render do
    header = """
    # Keyboard reference

    Generated by `mix swarm_code.keymap` from `SwarmCodeCLI.UI.Keymap.Bindings`.
    Do not edit by hand: `mix swarm_code.keymap --check` fails when this file
    and the table disagree.

    Keys are read against one *context* at a time, chosen from where the focus
    is and which layer is on top. `?` (or `F1` inside a text field) shows the
    same list for the current context on screen. Vim's NORMAL and VISUAL modes
    exist only with the vim keymap on (`SWARM_KEYMAP=vim`, or "Vim mode" in
    the command palette).

    #{@mouse_note}
    """

    header <> Enum.map_join(Bindings.contexts(), "", &context/1)
  end

  @doc "The human title of `context`."
  @spec title(atom()) :: binary()
  def title(context), do: Keyword.fetch!(@titles, context)

  @doc "The human title of `group`."
  @spec group_title(atom()) :: binary()
  def group_title(group), do: Keyword.fetch!(@groups, group)

  defp context(context) do
    bindings = Bindings.for_context(context)

    sections =
      Bindings.groups()
      |> Enum.map(fn group -> {group, Enum.filter(bindings, &(&1.group == group))} end)
      |> Enum.reject(fn {_group, rows} -> rows == [] end)
      |> Enum.map_join("", fn {group, rows} -> section(group, rows, context) end)

    "\n## " <> title(context) <> "\n" <> sections
  end

  defp section(group, rows, context) do
    table =
      Enum.map_join(rows, "\n", fn binding ->
        "| " <> keys(binding, context) <> " | " <> binding.help <> " |"
      end)

    "\n### " <> group_title(group) <> "\n\n| Keys | Does |\n|---|---|\n" <> table <> "\n"
  end

  # Only the spellings that reach the binding in this context: `?` opens help
  # in main, but in the composer it types, and only `F1` is listed there.
  defp keys(binding, context) do
    binding
    |> Bindings.keys_in_context(context)
    |> KeyLabel.labels(false)
    |> Enum.map_join(" / ", &("`" <> &1 <> "`"))
  end
end
