defmodule SwarmCodeCLI.UI.DataSource.DTO.AgentSummary do
  @moduledoc "Bounded, closed AgentSummary presentation facts."
  use SwarmCodeCLI.UI.DataSource.DTO.Schema,
    wire_defaults: [
      name: "",
      role: "unknown",
      title: "",
      step: "",
      progress: 0,
      tokens_in: 0,
      tokens_out: 0,
      cost_usd: nil,
      started_at: nil,
      finished_at: nil,
      parent_id: nil,
      depth: 0,
      changes_stat: nil,
      error: nil
    ],
    fields: [
      name: {:text, 200},
      role: {:enum, [:lead, :sub, :worker, :assistant, :judge, :unknown]},
      title: {:text, 200},
      step: {:text, 200},
      progress: :progress,
      tokens_in: :count,
      tokens_out: :count,
      cost_usd: {:optional, :float},
      started_at: {:optional, :count},
      finished_at: {:optional, :count},
      parent_id: {:optional, :id},
      depth: :count,
      changes_stat: {:optional, {:text, 200}},
      error: {:optional, {:text, 200}},
      id: :id,
      run_id: :id,
      revision: :revision,
      state:
        {:enum,
         [
           :queued,
           :running,
           :streaming,
           :waiting_question,
           :waiting_approval,
           :paused,
           :retrying,
           :done,
           :failed,
           :stopped,
           :interrupted,
           :superseded
         ]},
      allowed_actions: :actions,
      launched_by_superseded: :boolean
    ],
    defaults: [
      name: "",
      role: :unknown,
      title: "",
      step: "",
      progress: 0,
      tokens_in: 0,
      tokens_out: 0,
      cost_usd: nil,
      started_at: nil,
      finished_at: nil,
      parent_id: nil,
      depth: 0,
      changes_stat: nil,
      error: nil,
      id: nil,
      run_id: nil,
      revision: 0,
      state: :queued,
      allowed_actions: [],
      launched_by_superseded: false
    ]
end
