defmodule SwarmCodeCLI.UI.DataSource.DTO.RunSummary do
  @moduledoc "Bounded, closed RunSummary presentation facts."
  use SwarmCodeCLI.UI.DataSource.DTO.Schema,
    wire_defaults: [
      created_sequence: 0,
      parent_run_id: nil,
      seen_revision: 0,
      tokens_in: 0,
      tokens_out: 0,
      cost_usd: nil,
      model: nil,
      agents_total: 0,
      agents_running: 0,
      needs: 0,
      changes: 0,
      started_at: nil,
      finished_at: nil,
      consensus: false,
      error: nil,
      stop_reason: nil,
      error_kind: nil,
      stop_label: nil,
      provider_name: nil,
      retry_at: nil
    ],
    fields: [
      tokens_in: :count,
      tokens_out: :count,
      cost_usd: {:optional, :float},
      model: {:optional, {:text, 200}},
      agents_total: :count,
      agents_running: :count,
      needs: :count,
      changes: :count,
      started_at: {:optional, :count},
      finished_at: {:optional, :count},
      consensus: :boolean,
      error: {:optional, {:text, 200}},
      # pass70 C1: why the run stopped or failed (`SwarmCode.LLM.Error` kinds
      # and orchestration stop reasons, as words), the human label for it, the
      # provider that served `model`, and when a rate-limited request retries.
      stop_reason: {:optional, {:text, 64}},
      error_kind: {:optional, {:text, 64}},
      stop_label: {:optional, {:text, 64}},
      provider_name: {:optional, {:text, 200}},
      retry_at: {:optional, :count},
      created_sequence: :revision,
      parent_run_id: {:optional, :id},
      seen_revision: :revision,
      id: :id,
      conversation_id: :id,
      kind: {:enum, [:chat, :goal, :swarm, :workflow, :research, :consensus, :ultra]},
      title: :text,
      revision: :revision,
      state:
        {:enum,
         [
           :queued,
           :running,
           :streaming,
           :waiting_question,
           :waiting_approval,
           :paused,
           :retrying,
           :done,
           :failed,
           :stopped,
           :interrupted,
           :superseded
         ]},
      allowed_actions: :actions,
      progress: {:optional, :progress}
    ],
    defaults: [
      tokens_in: 0,
      tokens_out: 0,
      cost_usd: nil,
      model: nil,
      agents_total: 0,
      agents_running: 0,
      needs: 0,
      changes: 0,
      started_at: nil,
      finished_at: nil,
      consensus: false,
      error: nil,
      stop_reason: nil,
      error_kind: nil,
      stop_label: nil,
      provider_name: nil,
      retry_at: nil,
      created_sequence: 0,
      parent_run_id: nil,
      seen_revision: 0,
      id: nil,
      conversation_id: nil,
      kind: :chat,
      title: "",
      revision: 0,
      state: :queued,
      allowed_actions: [],
      progress: 0
    ]
end
