defmodule SwarmCodeCLI.UI.DataSource.DTO.WorkspaceSnapshot do
  @moduledoc "Bounded, closed WorkspaceSnapshot presentation facts."
  use SwarmCodeCLI.UI.DataSource.DTO.Schema,
    wire_defaults: [
      allowed_actions: [],
      revision: 0,
      seen_revision: 0,
      mode: nil,
      chat_model: nil,
      swarm_model: nil,
      effort: nil,
      swarm_effort: nil,
      project: nil,
      models: [],
      changes: [],
      verdicts: [],
      agents: [],
      approval_mode: nil,
      trusted: nil,
      chat_provider: nil,
      context_used: nil,
      context_window: nil,
      cost_usd: nil,
      title: nil,
      background: [],
      queued: 0
    ],
    fields: [
      project: {:optional, {:text, 200}},
      models: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.ModelOption}},
      agents: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.AgentSummary}},
      changes: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.Change}},
      verdicts: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.Verdict}},
      # pass70 C1: the project's approval mode (`read_only | auto |
      # full_access`) and trust (nil when the domain has no trust), the chat
      # model's provider name, the context gauge (tokens the next turn starts
      # from / the model's window), the conversation's total spend, its title,
      # and the background commands of the shown runs.
      approval_mode: {:optional, {:enum, [:read_only, :auto, :full_access]}},
      trusted: {:optional, :boolean},
      chat_provider: {:optional, {:text, 200}},
      context_used: {:optional, :count},
      context_window: {:optional, :count},
      cost_usd: {:optional, :float},
      title: {:optional, {:text, 256}},
      background: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.BackgroundCommand}},
      # pass71 S5: prompts of this conversation queued behind its live turn.
      queued: :count,
      allowed_actions: :actions,
      revision: :revision,
      seen_revision: :revision,
      runs_page: {:dto, SwarmCodeCLI.UI.DataSource.DTO.PageInfo},
      interactions_page: {:dto, SwarmCodeCLI.UI.DataSource.DTO.PageInfo},
      conversation_id: {:optional, :id},
      mode: {:optional, {:enum, [:build, :plan, :ultra, :workflow, :consensus]}},
      chat_model: {:optional, :text},
      swarm_model: {:optional, :text},
      effort: {:optional, :text},
      swarm_effort: {:optional, :text},
      runs: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.RunSummary}},
      transcript: {:dto, SwarmCodeCLI.UI.DataSource.DTO.TranscriptWindow},
      interactions: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.PendingInteraction}},
      state: {:enum, [:idle, :loading_before, :loading_after, :error, :closed, :resyncing]},
      before_cursor: {:optional, :id},
      after_cursor: {:optional, :id},
      request_id: {:optional, :id},
      error: {:optional, :error},
      presence: {:enum, [:covered, :off_window, :removed]},
      covered_ids: {:list, :id},
      through_sequence: :revision
    ],
    defaults: [
      project: nil,
      models: [],
      agents: [],
      changes: [],
      verdicts: [],
      approval_mode: nil,
      trusted: nil,
      chat_provider: nil,
      context_used: nil,
      context_window: nil,
      cost_usd: nil,
      title: nil,
      background: [],
      queued: 0,
      allowed_actions: [],
      revision: 0,
      seen_revision: 0,
      runs_page: nil,
      interactions_page: nil,
      conversation_id: nil,
      mode: nil,
      chat_model: nil,
      swarm_model: nil,
      effort: nil,
      swarm_effort: nil,
      runs: [],
      transcript: nil,
      interactions: [],
      state: :idle,
      before_cursor: nil,
      after_cursor: nil,
      request_id: nil,
      error: nil,
      presence: :covered,
      covered_ids: [],
      through_sequence: 0
    ]
end
