defmodule SwarmCodeCLI.UI.DataSource.DTO.WorkspaceSnapshot do
  @moduledoc "Bounded, closed WorkspaceSnapshot presentation facts."
  use SwarmCodeCLI.UI.DataSource.DTO.Schema,
    wire_defaults: [
      allowed_actions: [],
      revision: 0,
      seen_revision: 0,
      mode: nil,
      chat_model: nil,
      swarm_model: nil,
      effort: nil,
      swarm_effort: nil,
      project: nil,
      models: [],
      changes: [],
      verdicts: [],
      agents: [],
      approval_mode: nil,
      trusted: nil,
      chat_provider: nil,
      chat_provider_usable: nil,
      context_used: nil,
      context_window: nil,
      cost_usd: nil,
      title: nil,
      background: [],
      shells: [],
      queued: 0,
      queued_texts: [],
      git_branch: nil,
      git_dirty: nil,
      effort_levels: [],
      swarm_effort_levels: [],
      validator_model: nil,
      desktop_running: false,
      queued_count: 0,
      queue_paused: false,
      queue_revision: nil,
      effort_effective: nil,
      effort_source: nil,
      swarm_effort_effective: nil,
      swarm_effort_source: nil,
      scheduled_effort_default: nil,
      local_zone: nil
    ],
    fields: [
      project: {:optional, {:text, 200}},
      # pass74 S1-11 (R5): the service sends up to 400 models.
      models: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.ModelOption}, 400},
      agents: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.AgentSummary}},
      changes: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.Change}},
      verdicts: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.Verdict}},
      # pass70 C1: the project's approval mode (`read_only | auto |
      # full_access`) and trust (nil when the domain has no trust), the chat
      # model's provider name, the context gauge (tokens the next turn starts
      # from / the model's window), the conversation's total spend, its title,
      # and the background commands of the shown runs.
      approval_mode: {:optional, {:enum, [:read_only, :auto, :full_access]}},
      trusted: {:optional, :boolean},
      chat_provider: {:optional, {:text, 200}},
      # pass74 S1-11 (D11): whether that provider can answer (a key, or a
      # private-host base URL); false with no provider; nil when not known.
      chat_provider_usable: {:optional, :boolean},
      context_used: {:optional, :count},
      context_window: {:optional, :count},
      cost_usd: {:optional, :float},
      title: {:optional, {:text, 256}},
      background: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.BackgroundCommand}},
      # cli020 C15: the conversation's `!` shell commands, newest 50.
      shells: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.ShellItem}, 50},
      # pass71 S5: prompts of this conversation queued behind its live turn.
      queued: :count,
      # pass73 T3/T8: what waits there, oldest first (at most 20, 2 KB each).
      queued_texts: {:list, {:text, 2048}},
      # cli020 C22: the project's Git branch and how many paths changed (nil
      # outside a repository or when Git did not answer in 2 s).
      git_branch: {:optional, {:text, 80}},
      git_dirty: {:optional, :count},
      # cli020 C17: the levels /effort and /swarm_effort accept here, and the
      # validator model (the main model when the conversation names none).
      effort_levels: {:list, {:text, 32}, 16},
      swarm_effort_levels: {:list, {:text, 32}, 16},
      validator_model: {:optional, {:text, 256}},
      # cli020 C4: the ncode app is open on the same database.
      desktop_running: :boolean,
      # cli020 C1: the queue count (0.2.0 name), whether a user stop paused it, and the revision queue.edit compares (16 hex).
      queued_count: :count,
      queue_paused: :boolean,
      queue_revision: {:optional, {:text, 16}},
      # cli022 F4: the level each slot really uses (`effort`/`swarm_effort`
      # are the conversation's own, nil while it follows a default) and where
      # it came from: the conversation, this session's NCODE_EFFORT (chat
      # only) or Settings' default.
      effort_effective: {:optional, {:text, 32}},
      effort_source: {:optional, {:enum, [:conversation, :env, :default]}},
      swarm_effort_effective: {:optional, {:text, 32}},
      swarm_effort_source: {:optional, {:enum, [:conversation, :env, :default]}},
      # cli022 int (F1): Settings' scheduled effort and the Mac's zone, the
      # defaults a new scheduled task shows.
      scheduled_effort_default: {:optional, {:text, 32}},
      local_zone: {:optional, {:text, 64}},
      allowed_actions: :actions,
      revision: :revision,
      seen_revision: :revision,
      runs_page: {:dto, SwarmCodeCLI.UI.DataSource.DTO.PageInfo},
      interactions_page: {:dto, SwarmCodeCLI.UI.DataSource.DTO.PageInfo},
      conversation_id: {:optional, :id},
      mode: {:optional, {:enum, [:build, :plan, :ultra, :workflow, :consensus]}},
      chat_model: {:optional, :text},
      swarm_model: {:optional, :text},
      effort: {:optional, :text},
      swarm_effort: {:optional, :text},
      runs: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.RunSummary}},
      transcript: {:dto, SwarmCodeCLI.UI.DataSource.DTO.TranscriptWindow},
      interactions: {:list, {:dto, SwarmCodeCLI.UI.DataSource.DTO.PendingInteraction}},
      state: {:enum, [:idle, :loading_before, :loading_after, :error, :closed, :resyncing]},
      before_cursor: {:optional, :id},
      after_cursor: {:optional, :id},
      request_id: {:optional, :id},
      error: {:optional, :error},
      presence: {:enum, [:covered, :off_window, :removed]},
      covered_ids: {:list, :id},
      through_sequence: :revision
    ],
    defaults: [
      project: nil,
      models: [],
      agents: [],
      changes: [],
      verdicts: [],
      approval_mode: nil,
      trusted: nil,
      chat_provider: nil,
      chat_provider_usable: nil,
      context_used: nil,
      context_window: nil,
      cost_usd: nil,
      title: nil,
      background: [],
      shells: [],
      queued: 0,
      queued_texts: [],
      git_branch: nil,
      git_dirty: nil,
      effort_levels: [],
      swarm_effort_levels: [],
      validator_model: nil,
      desktop_running: false,
      queued_count: 0,
      queue_paused: false,
      queue_revision: nil,
      effort_effective: nil,
      effort_source: nil,
      swarm_effort_effective: nil,
      swarm_effort_source: nil,
      scheduled_effort_default: nil,
      local_zone: nil,
      allowed_actions: [],
      revision: 0,
      seen_revision: 0,
      runs_page: nil,
      interactions_page: nil,
      conversation_id: nil,
      mode: nil,
      chat_model: nil,
      swarm_model: nil,
      effort: nil,
      swarm_effort: nil,
      runs: [],
      transcript: nil,
      interactions: [],
      state: :idle,
      before_cursor: nil,
      after_cursor: nil,
      request_id: nil,
      error: nil,
      presence: :covered,
      covered_ids: [],
      through_sequence: 0
    ]
end
