#!/usr/bin/env python3
"""Generate/check the SafeText variation-pair table entirely offline."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import sys
import textwrap

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "third_party/unicode-17.0.0-variants"
OUTPUT = ROOT / "apps/swarm_code_cli/lib/swarm_code_cli/ui/safe_text/variants.ex"


def generate():
    manifest = json.loads((SOURCE / "UPSTREAM.json").read_text())
    pairs = set()
    for source in manifest["sources"]:
        path = SOURCE / source["file"]
        data = path.read_bytes()
        if len(data) != source["bytes"] or hashlib.sha256(data).hexdigest() != source["sha256"]:
            raise ValueError(f"source checksum mismatch: {path.relative_to(ROOT)}")
        if source["file"] == "UNICODE-LICENSE.txt":
            continue
        for line in data.decode("utf-8").splitlines():
            record = line.split("#", 1)[0].strip()
            if not record:
                continue
            sequence = record.split(";", 1)[0].split()
            if len(sequence) != 2:
                raise ValueError(f"unexpected Unicode sequence: {record}")
            base, selector = (int(cp, 16) for cp in sequence)
            if not (selector in [0x180B, 0x180C, 0x180D, 0x180F]
                    or 0xFE00 <= selector <= 0xFE0F
                    or 0xE0100 <= selector <= 0xE01EF):
                raise ValueError(f"unexpected selector: {selector:x}")
            pairs.add((base, selector))
    packed = b"".join(base.to_bytes(3, "big") + selector.to_bytes(3, "big")
                      for base, selector in sorted(pairs))
    payload = textwrap.indent("\n".join(textwrap.wrap(base64.b64encode(packed).decode(), 96)), "           ")
    result = '''defmodule SwarmCodeCLI.UI.SafeText.Variants do
  @moduledoc """
  Attested Unicode 17.0.0 standardized/emoji and IVD 2025-07-14 pairs.

  Generated by scripts/dev/sync_unicode_variants.py. Unicode License V3;
  preserved sources and checksums: third_party/unicode-17.0.0-variants/.
  Each sorted record is a 24-bit base followed by a 24-bit selector.
  """
  @pairs Base.decode64!(
           """
PAYLOAD
           """,
           ignore: :whitespace
         )
  @count COUNT

  @spec valid?(non_neg_integer(), non_neg_integer()) :: boolean()
  def valid?(base, selector)
      when is_integer(base) and base in 0..0x10FFFF and is_integer(selector) and
             selector in 0..0x10FFFF,
      do: find(<<base::24, selector::24>>, 0, @count - 1)

  def valid?(_, _), do: false

  defp find(_key, low, high) when low > high, do: false

  defp find(key, low, high) do
    middle = div(low + high, 2)
    candidate = binary_part(@pairs, middle * 6, 6)

    cond do
      key == candidate -> true
      key < candidate -> find(key, low, middle - 1)
      true -> find(key, middle + 1, high)
    end
  end
end
'''.replace("PAYLOAD", payload).replace("COUNT", str(len(pairs)))
    return result, len(pairs)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result, count = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != result:
            raise ValueError("generated variation table differs; run sync_unicode_variants.py")
        print(f"Verified source hashes and generated table: {count} attested pairs")
    else:
        OUTPUT.write_text(result)
        print(f"Generated {OUTPUT.relative_to(ROOT)}: {count} attested pairs")


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
